apiVersion: apps/v1
kind: Deployment
metadata:
  name: apartments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apartments
  template:
    metadata:
      labels:
        app: apartments
    spec:
      containers:
        - image: frijugsincek/apartments:2020-12-03-03-38-42
          name: apartments
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://suleiman.db.elephantsql.com:5432/bfztibdg
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: bfztibdg
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: vnesi-geslo
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: apartments
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: apartments