apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching
  template:
    metadata:
      labels:
        app: matching
    spec:
      containers:
        - image: frijugsincek/matching:2021-01-03-19-57-13
          name: matching
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://suleiman.db.elephantsql.com:5432/bidrgpur
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: bidrgpur
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matching-pass
                  key: KUMULUZEE_DATASOURCES0_MATCHING_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

# apiVersion: v1
# kind: Service
# metadata:
#   name: matching
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8080
#       protocol: TCP
#       targetPort: server
#   selector:
#     app: matching

apiVersion: v1
kind: Service
metadata:
  name: matching
spec:
  selector:
    app: matching
  ports:
    - name: web
      port: 8080
  type: ClusterIP