kumuluzee:
  name: matching-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/MatchingDS
      connection-url: jdbc:postgresql://localhost:5432/matching
      username: dbuser
      password: postgres
      pool:
        max-size: 3
  cors-filter:
    servlet:
      allow-origin: "*"
      allow-subdomains: true
      supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"