kumuluzee:
  name: matching-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/MatchingDS
      connection-url: jdbc:postgresql://localhost:5432/matching
      username: dbuser
      password: postgres
      max-pool-size: 20
