kumuluzee:
  name: matching-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/MatchingDS
      connection-url: jdbc:postgresql://localhost:5432/matching
      username: dbuser
      password: postgres
      pool:
        max-size: 3
  cors-filter:
    servlet:
      allow-origin: "*"
      allow-subdomains: true
      supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="82e011f8-ddec-4e50-a0fd-9436b992a086-ls.logit.io"
                                  port="10195" protocol="udp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="trace" />
                                  </Root>
                              </Loggers>
                          </Configuration>'